---
site_name: Donkey Car 中文说明
theme: readthedocs

nav:
  - 首页: index.md
  - 硬件架构: wiki/hardware_arch.md
  - 软件架构: wiki/software_arch.md
  - 机械架构: wiki/mechanic_arch.md
  - 操作流程: wiki/dk_process.md
  - 驾驶技巧: wiki/drive_tips.md
  - 关于我们: wiki/aboutus.md
